name: Portfolio

on: 
    push: 
        branches: [main]

permissions:
        pages: write
        id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployments.outputs.url }}

        steps: 
            #getaccess to ur portfolio code via prebuilt 
            - name: checkout code
              uses: actions/checkout@v4

            #setup github pages 
            - name: Setup Github pages
              uses: actions/configure-pages@v4

            # static code artifacts 
            - name: static code 
              uses: actions/upload-pages-artifacts@v4
            
            - name: DEploy to github pages
              uses: actions/deploy-pages@v4
