name: Portfolio

on: 
  push: 
    branches: [main]
  workflow_dispatch:
    

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps: 
      # Get access to repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Upload static site files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # folder where your index.html is

      # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4